### PR TITLE
Add remaining 8.xx

### PR DESCRIPTION
**Pull request by Al-Azif**
- 8.00, 8.01, and 8.03 offsets all appear to be the same
- 8.52 appears to match 8.50
- 9.51 appears to match 9.50/9.60

Untested, just happened to have 99% off the offsets from other stuff

### CODE REVIEW

**Comment by iMrDJAi** [comment]
@Al-Azif Awesome! Was going to begin working on FW 8.00. Thank you so much for your contribution!

**Comment by Al-Azif** [comment]
Any reason why @kmeps4 opened up a new PR, without putting me as a co-author even, rather than just confirming this commit works? As now this PR is in conflict.

**Comment by kmeps4** [comment]
> Any reason why @kmeps4 opened up a new PR, without putting me as a co-author even, rather than just confirming this commit works? As now this PR is in conflict.

Sorry Azif but I also fixed some typo you had on the stage1 and stage2 and one bad offset as oxf0xf typo also... I didn't saw any issues doing a PR with the fixes.. credits are all yours!!!

**Comment by Al-Azif** [comment]
Normally you'd commit to my branch and co-authoring is done like this https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors. I'm mentioned in the PR title

**Comment by iMrDJAi** [comment]
A strategic mistake I see here 🫠

**Comment by Al-Azif** [comment]
Well this PR matches the repo now, just with some semblance of proper credit

**Comment by fabianlanza** [comment]
> Any reason why @kmeps4 opened up a new PR, without putting me as a co-author even, rather than just confirming this commit works? As now this PR is in conflict.

Dam lol

**Pull request merged**
