### PR TITLE
Added PS4 7.00 7.01 7.02 Offsets

### PR DESCRIPTION
**Pull request by EchoStretch**
Someone asked for 7.02. Enjoy, it ought to function properly.
Testing is required, but all 7.00 offsets align with those of 7.02.

### CODE REVIEW

**Comment by DarkWhisper** [comment]
Stage 3 always results in a Kernel Panic / Sudden shutdown. This was tested around 8-10 times on my 7.02 PS4.
PS4_KP

**Comment by Zenzeq** [comment]
> Stage 3 always results in a Kernel Panic / Sudden shutdown. This was tested around 8-10 times on my 7.02 PS4. PS4_KP

Same issue with me. I barely get past stage 1 and stage 2 is a rare sight. By the time it progresses past KASLR it'll freeze and kernel panic. I'm wondering if one or more of the offsets are wrong or if it's the firmware security? Perhaps the script needs adjusting?

**Comment by EchoStretch** [comment]
Hey, I appreciate your help with testing. I'll have some time over the weekend to review them again. Initially, I ran the tests with version 702 and then cross-checked with version 700, but there might be something I miss.

**Comment by Zenzeq** [comment]
> Hey, I appreciate your help with testing. I'll have some time over the weekend to review them again. Initially, I ran the tests with version 702 and then cross-checked with version 700, but there might be something I miss.

I managed to compile ppyn C++ with your changes to the script and got it working for macOS High Sierra and have doubled the time to check by about 80% so testing goes much, much quicker. One issue I've found is it'll fail on [-] Scanning for corrupted object...failed. about 10-15 times (I have it set on --auto-retry) until it gets to the second stage, then kernel panics. Thanks again for your help!

**Comment by EchoStretch** [comment]
Ok, I did find that memcpy appeared to be correct, but it actually wasn't. Feel free to try it if you'd like. I will check stage 1 and stage 2 tomorrow.

**Comment by DarkWhisper** [comment]
> Ok, I did find that memcpy appeared to be correct, but it actually wasn't. Feel free to try it if you'd like. I will check stage 1 and stage 2 tomorrow.

I'm getting successful stage2 execution on 7.02. (i.e. the console's displaying the "PPPwned" notification)

Based on the last 40 attempts, the success rate is ~60% with all other attempts failing to find the corrupted object during the memory corruption stage.

I did get two kernel panics on my first and fourth attempts (not included in the success rate measurement), but I think these were both due to user error / not waiting for "Cannot connect to network: (NW-31274-7)".

**Comment by EchoStretch** [comment]
Yes, I get the same results with version 7.55. I believe you'll achieve better results using C++ instead of Python. When I have some time, I'll plug in my 7.55 and give it a try.

Thank You For Confirming It Works.

**Pull request merged**
